config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("publishing.books.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publishing/books/urls.py
from django.urls import path

from . import views


app_name = "books"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("publishers/", views.PublisherListView.as_view(), name="publisher_list"),
    path(
        "publishers/<int:pk>/",
        views.PublisherDetailView.as_view(),
        name="publisher_detail",
    ),
    path(
        "publishers/add/", views.PublisherCreateView.as_view(), name="publisher_create"
    ),
    path(
        "publishers/<int:pk>/books/edit/",
        views.PublisherBooksUpdateView.as_view(),
        name="publisher_books_update",
    ),
]

publishing/books/models.py
from django.db import models
from django.urls import reverse


class Publisher(models.Model):
    name = models.CharField(null=False, blank=False, max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("books:publisher_detail", kwargs={"pk": self.pk})


class Book(models.Model):
    title = models.CharField(null=False, blank=False, max_length=255)

    publisher = models.ForeignKey(
        "Publisher",
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name="books",
    )

    def __str__(self):
        return self.title


class BookImage(models.Model):
    "e.g. image of the cover, backcover, etc."

    book = models.ForeignKey(
        "Book", null=False, blank=False, on_delete=models.CASCADE, related_name="images"
    )

    image = models.ImageField(null=False, blank=False, max_length=255)

    alt_text = models.CharField(null=False, blank=True, max_length=255)

publishing/books/forms.py
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.utils.translation import gettext_lazy as _

from publishing.utils.forms import is_empty_form, is_form_persisted
from .models import Publisher, Book, BookImage


# The formset for editing the BookImages that belong to a Book.
BookImageFormset = inlineformset_factory(
    Book, BookImage, fields=("image", "alt_text"), extra=1
)


class BaseBooksWithImagesFormset(BaseInlineFormSet):
    """
    The base formset for editing Books belonging to a Publisher, and the
    BookImages belonging to those Books.
    """

    def add_fields(self, form, index):
        super().add_fields(form, index)

        # Save the formset for a Book's Images in the nested property.
        form.nested = BookImageFormset(
            instance=form.instance,
            data=form.data if form.is_bound else None,
            files=form.files if form.is_bound else None,
            prefix="bookimage-%s-%s"
            % (form.prefix, BookImageFormset.get_default_prefix()),
        )

    def is_valid(self):
        """
        Also validate the nested formsets.
        """
        result = super().is_valid()

        if self.is_bound:
            for form in self.forms:
                if hasattr(form, "nested"):
                    result = result and form.nested.is_valid()

        return result

    def clean(self):
        """
        If a parent form has no data, but its nested forms do, we should
        return an error, because we can't save the parent.
        For example, if the Book form is empty, but there are Images.
        """
        super().clean()

        for form in self.forms:
            if not hasattr(form, "nested") or self._should_delete_form(form):
                continue

            if self._is_adding_nested_inlines_to_empty_form(form):
                form.add_error(
                    field=None,
                    error=_(
                        "You are trying to add image(s) to a book which "
                        "does not yet exist. Please add information "
                        "about the book and choose the image file(s) again."
                    ),
                )

    def save(self, commit=True):
        """
        Also save the nested formsets.
        """
        result = super().save(commit=commit)

        for form in self.forms:
            if hasattr(form, "nested"):
                if not self._should_delete_form(form):
                    form.nested.save(commit=commit)

        return result

    def _is_adding_nested_inlines_to_empty_form(self, form):
        """
        Are we trying to add data in nested inlines to a form that has no data?
        e.g. Adding Images to a new Book whose data we haven't entered?
        """
        if not hasattr(form, "nested"):
            # A basic form; it has no nested forms to check.
            return False

        if is_form_persisted(form):
            # We're editing (not adding) an existing model.
            return False

        if not is_empty_form(form):
            # The form has errors, or it contains valid data.
            return False

        # All the inline forms that aren't being deleted:
        non_deleted_forms = set(form.nested.forms).difference(
            set(form.nested.deleted_forms)
        )

        # At this point we know that the "form" is empty.
        # In all the inline forms that aren't being deleted, are there any that
        # contain data? Return True if so.
        return any(not is_empty_form(nested_form) for nested_form in non_deleted_forms)


# This is the formset for the Books belonging to a Publisher and the
# BookImages belonging to those Books.
#
# You'd use this by passing in a Publisher:
#     PublisherBooksWithImagesFormset(**form_kwargs, instance=self.object)
PublisherBooksWithImagesFormset = inlineformset_factory(
    Publisher,
    Book,
    formset=BaseBooksWithImagesFormset,
    # We need to specify at least one Book field:
    fields=("title",),
    extra=1,
    # If you don't want to be able to delete Publishers:
    # can_delete=False
)

publishing/utils/forms.py
def is_empty_form(form):
    """
    A form is considered empty if it passes its validation,
    but doesn't have any data.

    This is primarily used in formsets, when you want to
    validate if an individual form is empty (extra_form).
    """
    if form.is_valid() and not form.cleaned_data:
        return True
    else:
        # Either the form has errors (isn't valid) or
        # it doesn't have errors and contains data.
        return False


def is_form_persisted(form):
    """
    Does the form have a model instance attached and it's not being added?
    e.g. The form is about an existing Book whose data is being edited.
    """
    if form.instance and not form.instance._state.adding:
        return True
    else:
        # Either the form has no instance attached or
        # it has an instance that is being added.
        return False

publishing/books/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DetailView,
    FormView,
    ListView,
    TemplateView,
)
from django.views.generic.detail import SingleObjectMixin

from .forms import PublisherBooksWithImagesFormset
from .models import Publisher, Book, BookImage


class HomeView(TemplateView):
    template_name = "books/home.html"


class PublisherListView(ListView):
    model = Publisher
    template_name = "books/publisher_list.html"


class PublisherDetailView(DetailView):
    model = Publisher
    template_name = "books/publisher_detail.html"


class PublisherCreateView(CreateView):
    """
    Only for creating a new publisher. Adding books to it is done in the
    PublisherBooksUpdateView().
    """

    model = Publisher
    template_name = "books/publisher_create.html"
    fields = [
        "name",
    ]

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, "The publisher was added.")

        return super().form_valid(form)


class PublisherBooksUpdateView(SingleObjectMixin, FormView):
    """
    For adding books to a Publisher, or editing them.
    """

    model = Publisher
    template_name = "books/publisher_books_update.html"

    def get(self, request, *args, **kwargs):
        # The Publisher we're editing:
        self.object = self.get_object(queryset=Publisher.objects.all())
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # The Publisher we're uploading for:
        self.object = self.get_object(queryset=Publisher.objects.all())
        return super().post(request, *args, **kwargs)

    def get_form(self, form_class=None):
        """
        Use our big formset of formsets, and pass in the Publisher object.
        """
        return PublisherBooksWithImagesFormset(
            **self.get_form_kwargs(), instance=self.object
        )

    def form_valid(self, form):
        """
        If the form is valid, redirect to the supplied URL.
        """
        form.save()

        messages.add_message(self.request, messages.SUCCESS, "Changes were saved.")

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("books:publisher_detail", kwargs={"pk": self.object.pk})

publishing/templates/books/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block page_title %}{% endblock %}</title>

    <style type="text/css">
      body {
        background: #fff;
        color: #000;
        font-family: Helvetica, Arial, sans-serif;
        line-height: 1.4em;
        margin: 2em 30px 3em 30px;
      }

      table {
        border-collapse: collapse;
        border-bottom: 1px solid #ccc;
        margin-bottom: 1em;
      }
      th, td {
        text-align: left;
        vertical-align: top;
        padding: 0.5em 5px;
        border-top: 1px solid #ccc;
      }

      table table tr:first-child th,
      table table tr:first-child td {
        border-top: none;
      }

      img {
        padding: 3px;
        border: 1px solid #ccc;
        width: auto;
      }

      td img {
        vertical-align: top;
      }

      hr {
        border: 0;
        border-top: 1px solid #999;
        margin: 1em 0;
      }

      .indent {
          margin-left: 40px;
      }

    </style>
  </head>
  <body>

    <h1>{% block body_title %}{% endblock %}</h1>

    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    <main>
      {% block content %}
      {% endblock content %}
    </main>

  </body>
</html>

publishing/templates/books/home.html
{% extends 'books/base.html' %}

{% block page_title %}Home{% endblock %}

{% block body_title %}Home{% endblock %}


{% block content %}

  <p>
    <a href="{% url 'books:publisher_list' %}">All publishers</a>
    |
    <a href="{% url 'books:publisher_create' %}">Add a publisher</a>
  </p>

{% endblock content %}

publishing/templates/books/publisher_books_update.html
{% extends 'books/base.html' %}

{% block page_title %}Editing books for {{ publisher.name }}{% endblock %}

{% block body_title %}Editing books for <a href="{{ publisher.get_absolute_url }}">{{ publisher.name }}</a>{% endblock %}


{% block content %}
  <form action="" method="post" enctype="multipart/form-data">

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}

    {% csrf_token %}

    {{ form.management_form }}
    {{ form.non_form_errors }}

    {% for book_form in form.forms %}

      <hr>

      <h2>
        {% if book_form.instance.id %}
          Book #{{ book_form.instance.id }}</h2>
        {% else %}
          {% if form.forms|length > 1 %}
            Add another book
          {% else %}
            Add a book
          {% endif %}
        {% endif %}
      </h2>

      {% for hidden_field in book_form.hidden_fields %}
        {{ hidden_field.errors }}
      {% endfor %}

      <table>
        {{ book_form.as_table }}
      </table>

      {% if book_form.nested %}
        <div class="indent">

          <h3>Images</h3>

          {{ book_form.nested.management_form }}
          {{ book_form.nested.non_form_errors }}

          <table>
            {% for bookimage_form in book_form.nested.forms %}

              <tr>
                <td>
                  <em>
                    {% if bookimage_form.instance.id %}
                      BookImage #{{ bookimage_form.instance.id }}
                    {% else %}
                      Add an image
                    {% endif %}
                  </em>
                </td>
                <td>
                  {% for hidden_field in bookimage_form.hidden_fields %}
                    {{ hidden_field.errors }}
                  {% endfor %}

                  <table>
                    {{ bookimage_form.as_table }}
                  </table>
                </td>
                <td>
                  {% if bookimage_form.instance.image %}
                    <img src="{{ bookimage_form.instance.image.url }}" height="100" alt="{{ nested.form.instance.alt_text }}">
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </table>
        </div>
      {% endif %}

    {% endfor %}

    <hr>

    <p>
      <input type="submit" value="Update books">
      &nbsp; &nbsp;
      <a href="{{ publisher.get_absolute_url  }}">Cancel</a>
    </p>
  </form>

{% endblock content %}

publishing/templates/books/publisher_create.html
{% extends 'books/base.html' %}

{% block page_title %}Adding a publisher{% endblock %}

{% block body_title %}Adding a publisher{% endblock %}


{% block content %}
  <form action="" method="post">

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}

    {% csrf_token %}

    {{ form.non_form_errors }}

    <table>
      {{ form.as_table }}
    </table>

    <p>
      <input type="submit" value="Add publisher">
      &nbsp; &nbsp;
      <a href="{% url 'books:home' %}">Cancel</a>
    </p>
  </form>

{% endblock content %}

publishing/templates/books/publisher_detail.html
{% extends 'books/base.html' %}

{% block page_title %}{{ publisher.name }}{% endblock %}

{% block body_title %}{{ publisher.name }}{% endblock %}


{% block content %}


  <h2>Books</h2>

  {% if publisher.books.all %}

    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Images</th>
        </tr>
      </thead>
      <tbody>
        {% for book in publisher.books.all %}
          <tr>
            <td>{{ book.id }}</td>
            <td>{{ book.title }}</td>
            <td>
              {% if book.images.all %}
                {% for image in book.images.all %}
                  <img src="{{ image.image.url }}" height="100" alt="{{ image.alt_text }}">
                {% endfor %}
              {% else %}
                (None)
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  {% else %}

    <p>This publisher has no books.</p>

  {% endif %}

  <p>
    <a href="{% url 'books:publisher_books_update' pk=publisher.pk %}">
      {% if publisher.books.all %}
        Edit these books
      {% else %}
        Add some books
      {% endif %}
    </a>
    |
    <a href="{% url 'books:publisher_list' %}">All publishers</a>
  </p>

{% endblock content %}

publishing/templates/books/publisher_list.html
{% extends 'books/base.html' %}

{% block page_title %}Publishers{% endblock %}

{% block body_title %}Publishers{% endblock %}


{% block content %}

  {% if publisher_list %}

    <ul>
      {% for publisher in publisher_list %}
        <li>
          <a href="{{ publisher.get_absolute_url }}">{{ publisher.name }}</a>
          ({{ publisher.books.count }} book{{ publisher.books.count|pluralize }})
        </li>
      {% endfor %}
    </ul>

  {% else %}

    <p>There are no publishers to display.</p>

  {% endif %}

  <p>
    <a href="{% url 'books:publisher_create' %}">Add a publisher</a>
  </p>

{% endblock content %}